04-Imperative.ipynb
solutions/Imperative-02.py
solutions/Imperative-03.py

Exercise for computing pi using Monte Carlo methods.

Add pi computation to imperative notebook

---

Dockerfile

If you're interested in a Dockerfile, this one can be used to run the tutorial and example notebooks:
```
docker build -t dask .
docker run -p 8888:8888 dask
```

Adding a Dockerfile

---

Dockerfile

Sorry--I forgot that the version I committed was python3.  This does the setup for both python2 and python3 in the image.

Added python2 support to Dockerfile

---

01-Array.ipynb
03b-DataFrame-Storage.ipynb
05-Bag.ipynb
README.md

Update links throughout

---

README.md

Some of us have the 'pleasure' of working on Windows and this would just remove a little of the friction.

Added instructions on installing graphviz on Windows

---

README.md

Overlooked README.md in the previous change.

Changed do to delayed

---

01_overview.ipynb
04_distributed.ipynb
06_distributed_advanced.ipynb
Dockerfile
README.md

Also, tidy up dockerfile (if anyone is using that), and mention recreate_error_locally

Rewrite README outline

---

Dockerfile

the graph visualization weren't working before when using the docker image

adds python-graphviz package and fixes issue #35

---

README.md
environment.yaml

Include env.yaml and change README to use it

---

README.md

Added two conda commands that make installing graphviz on windows easier.
source: https://github.com/ContinuumIO/anaconda-issues/issues/485#issuecomment-279296254

Alternative Windows Installation of graphviz

---

README.md

Correcting typo in readme

---

README.md

Someone pointed out the inconsistency.
Fixes #49

Change environment.yaml to .yml to match file name

---

README.md

Format some of the instructions for Windows

---

README.md

Docker info

---

README.md

This will help someone like me who does not have enough docker knowledge and hopefully will save hours to find that it is not possible to access 8888 port without `-p` argument.

Elaborates how to run this on docker

---

README.md

Follow up to #92 and some more details from #91

Update README a little

---

04_dataframe.ipynb

"grant total" => "grand total"

Typo in notebook

---

01_dask.delayed.ipynb
02_bag.ipynb
03_array.ipynb
04_dataframe.ipynb
08_machine_learning.ipynb
prep.py

- Fixes a few typos found in the notebooks.
- Adds the option to disable ssl-verify in prep.py

Updates to allow the tutorial to run behind institutional firewall

---

00_overview.ipynb

fix dask StackOverflow tag in overview

---

binder/environment.yml

That makes ipywidgets work on binder.

Pin jupyterlab

---

binder/environment.yml

Closes https://github.com/dask/dask-tutorial/issues/132 (maybe)

Install python dask-labextension

---

.travis.yml
binder/environment.yml
prep.py

Adds a `--small` flag, to let us run this as part of CI / on binder.
In general, I've tried to keep the number of files / partitions the same, just smaller.

Rework prep

---

.gitignore
01_dask.delayed.ipynb
02_bag.ipynb
03_array.ipynb
04_dataframe.ipynb
05_distributed.ipynb
06_distributed_advanced.ipynb
binder/environment.yml
binder/jupyterlab-workspace.json
binder/postBuild
binder/start
prep.py
solutions/Array-03.py

This starts a largish change, to use the distributed scheduler for every notebook. We still don't explain schedulers until later.
I believe we've done this in past tutorials, and it's worked well enough. I'll do this for the rest of the notebooks, but wanted to see if there are any objections first.

Use distributed scheduler

---

binder/start
prep.py

Running the large datasets on binder is a bit painful. This uses the small datasets via an environment variable.

Set environment variable for small datasets

---

08_machine_learning.ipynb

update cluster link

---

04_dataframe.ipynb
08_machine_learning.ipynb

Drop nbytes cell

---

00_overview.ipynb
01_dask.delayed.ipynb
01x_lazy.ipynb
02_bag.ipynb
03_array.ipynb
05_distributed.ipynb
06_distributed_advanced.ipynb
07_dataframe_storage.ipynb
Homework.ipynb
README.md
prep.py

Move the prep data to the notebooks

---

binder/environment.yml

(and also many other packages)
Fixes #163

Update dask to 2.11

---

01_dask.delayed.ipynb
01x_lazy.ipynb
02_bag.ipynb
03_array.ipynb
06_distributed_advanced.ipynb
binder/environment.yml

This PR hides a few exercise solutions that currently displayed by default. Here's the binder link for the tutorial with the changes in this PR: https://mybinder.org/v2/gh/jrbourbeau/dask-tutorial/hide-solution-cells
Closes #155

Hide solutions cells

---

01x_lazy.ipynb

Thanks for these great tutorials! I'd like to propose a fix to #122

fix broken sentence (fixes #122)

---

06_distributed_advanced.ipynb

- Updated scheduler config for debugging
- Added magic `%debug`
- One more debugging technique

Distributed Advanced Updates

---

00_overview.ipynb
01_dask.delayed.ipynb
05_distributed.ipynb

This PR has a few small updates (mostly typos)

A few small updates

---

00_overview.ipynb

Closes https://github.com/dask/dask-tutorial/issues/186

DOC: update links

---

index.rst

Follow up to https://github.com/dask/dask-tutorial/pull/196. I forgot to also update the video on https://tutorial.dask.org

Update to SciPy 2020 video on webpage

---

.github/workflows/ci-build.yaml

Closes https://github.com/dask/dask-tutorial/issues/209

Fix conda solve issue in CI

---

conf.py
index.rst

Link: https://mybinder.org/v2/gh/freyam/dask-tutorial/main

Updated Binder Badge Image

---

.github/workflows/ci-repo2docker.yaml

As title 
xref https://github.com/dask/dask-tutorial/pull/216

Fix CI build issues

---

prep.py

Just a quick fix for a typo I encountered while going through the tutorial

Fix typo in prep.py: acccouts -> accounts

---

.github/workflows/ci-repo2docker.yaml
03_array.ipynb
04_dataframe.ipynb
06_distributed_advanced.ipynb
Homework.ipynb

Running [codespell](https://github.com/codespell-project/codespell) revealed some typos.  This PR fixes typos discovered in this way.

Fix typos discovered by codespell

---

README.md

Closes https://github.com/dask/dask-tutorial/issues/222. This can also be removed once https://github.com/dask/dask-tutorial/pull/207 is in

Add Dask labextension instructions to README

---

.gitignore
04_dataframe.ipynb
binder/environment.yml
prep.py

Added a join example to the tutorial as discussed in [dask](https://github.com/dask/dask/issues/6593). Since the tutorial is using real data, I have added a holidays dataset to be used in the join. Not sure if the added dependency is okay though.

add join example to dataframe tutorial

---

01x_lazy.ipynb
06_distributed_advanced.ipynb
08_machine_learning.ipynb

Fixes a few small typos scattered across multiple notebooks.

Fix typos in notebooks

---

00_overview.ipynb

xref https://github.com/dask/dask-tutorial/issues/239#issuecomment-1155363684
cc @scharlottej13 @pentschev

Fix logo in overview notebook

---

index.rst

This _should_ put the right links in the index of the website

Fix TOC so that website builds

---

01_dataframe.ipynb
02_array.ipynb
03_dask.delayed.ipynb
04_distributed.ipynb
05_futures.ipynb

I mostly did dataframe in this PR, but also made the titles a little longer in all the notebooks.

First pass at reading over notebooks

---

01_dataframe.ipynb

Updated this section with @ncclementi's help. :)

Update dataframe notebook's map_partitions section

---

.github/workflows/ci-repo2docker.yaml
binder/environment.yml

https://github.com/jrbourbeau/dask-binder-template

Simplify docker build action for binder

---

00_overview.ipynb
README.md
binder/environment.yml

I had removed it from the env, but the new overview depends on it.

Add pyarrow and s3fs to readme

---

01_dataframe.ipynb
02_array.ipynb
03_dask.delayed.ipynb

I tried to spot all the solution cells and hide them.

Hide solution cells

---

binder/start

Fix Dask Dashboard link

---

README.md
binder/environment.yml

@jacobtomlinson and I are presenting a 90 min tutorial at the ESIP winter meeting on Jan 25th.

ESIP 2023 tutorial

---

.github/workflows/ci-build.yaml

See https://github.com/dask/dask-sphinx-theme/pull/84
cc @jacobtomlinson @emily-d-anderson

update dask-sphinx-theme for GA-4
