01-Array.ipynb

Reverses the %matplotlib inline magic and import statement (required on mac).
Note that I'm also using Python 3 and a newer version of IPython.

updated matplotlib inline and import to work on mac

---

03a-DataFrame.ipynb

`_visualize()` no longer works with current versions of dask.

Replace outdated _visualize() calls with visualize()

---

README.md

README file had a mix of markdown and reStructuredText, and most of it is rendered by GitHub as a block of code.
This PR replaces rst syntax by markdown, so it's rendered properly.

Fixing README file format

---

02_foundations.ipynb

The text mentions `Dockerfile`, but the two code blocks that follow operate on `README.md` instead. Make the text match the code.

Make filename in text match that in code

---

environment.yml
prep.py

Replaced deprecated scipy.misc.imresize import by skimage.transform.resize in create_weather(). Changed growth argument accordingly. Added scikit-image to environment.yml.
Didn't know or check if scipy was used elsewhere in the code. If not used elsewhere it can be removed from environment.yml I suppose.

Fix ImportError caused by deprecated scipy.misc.imresize

---

02_foundations.ipynb

Small change in tutorial. 
Change cell that has example code with elypsis "..." from code to markdown to prevent it from raising an error. 
use ```python and markdown cell for code example that shouldn't run.

replace code cell with markdown

---

06_distributed_advanced.ipynb

Fix #65.
I tackled the comments in:
* https://github.com/dask/dask-tutorial/issues/65#issuecomment-373338992
* https://github.com/dask/dask-tutorial/issues/65#issuecomment-373346335
Also I could not find anywhere in the previous notebooks that generated the json.gz files so I added a cell using `prep.accounts_json`.

Fix 06_distributed_advanced.ipynb

---

prep.py

Since data/ exists at clone, we do not have to check that it exists, let
alone twice. However, adding a check that there are
small-weather/*.hdf5 files as a "just in case" check.

Remove 2 data/ existence checks, add small-weather check

---

environment.yml

@bmcguirk , please check with this env - python is fixed to v36.
Ref: https://github.com/dask/dask-tutorial/issues/78

Keep to py36 for now

---

prep.py

The default is changing in the future. This produced a warning when running prep.py

scikit-image compat

---

01_dask.delayed.ipynb

This PR corrects typo in tutorial 01_dask_delayed.ipynb
specifically 'ane-another' -> 'one-another'

Fix typo 'ane-another' -> 'one-another' in tutorial #01

---

README.md

This PR updates README.md, video tutorial link to a more recent version.
Not sure if it was intended to keep the 2017 version, but It seems like there is a more recent version of the video tutorial.: https://www.youtube.com/watch?v=mqdglv9GnM8

Replace video tutorial link to more recent one

---

conf.py

PR updates conf.py to use dask-tutorial instead of dask-examples for binder links

update binder links

---

index.rst

Fixes SciPy 2018 YouTube link

---

02_bag.ipynb
07_dataframe_storage.ipynb
Dockerfile

PR adds moves prep call (downloading data) to postBuild and also adds anon option to s3 calls

more fixes

---

01x_lazy.ipynb

Resolves #121 
Don't exactly know why but converting to markdown seems to have fixed the issue:
From local build log:
```
Generating indices... genindex
writing additional pages... search
copying images... [ 33%] images/grid_search_schedule.gif
copying images... [ 66%] images/tasks.png
copying images... [100%] images/merged_grid_search_graph.svg
```
I think I saw something in `docutilis` which checks for `alt text` when parsing docs --this is added when using markdown

use markdown for gif

---

07_dataframe_storage.ipynb

Escape quotes in cell with call to .to_parquet()

Restore 07_dataframe_storage.ipynb to valid JSON

---

01_dask.delayed.ipynb

This section heading is showing up in the toctree

Lower heading level in dask delayed notebook

---

.github/workflows/ci-repo2docker.yaml
binder/environment.yml
binder/postBuild

We're temporarily pinning JupyterLab and the dask lab extension to avoid issues with other JL extensions that aren't compatible with JupyterLab 2.0 yet (xref https://github.com/dask/dask-tutorial/pull/165#issuecomment-595276955)
I've also added a GitHub Actions workflow to our CI that runs `repo2docker` on the tutorial to test that binder deployments will work

Pin JupyterLab to 1.x and add repo2docker CI build

---

binder/environment.yml

This PR bumps both Jupyterlab and dask-labextension to their latest releases (2.0.0).

Bump jupyterlab and dask-labextension to 2.x

---

prep.py

I think that `zipfile` is unused in `prep.py`, and I'd like to propose removing it.

remove unused import in prep.py

---

.gitignore

Thanks for these tutorials!
I found that one of them creates a directory `dask-worker-space`. I think that's coming from [`distributed.worker`](https://distributed.dask.org/en/latest/_modules/distributed/worker.html).
In this PR, I propose adding it to `.gitignore`.

add dask-worker-space to gitignore

---

binder/environment.yml

This PR updates Python and Dask to the latest supported releases

Bump Python to 3.8 and Dask to 2.20.0

---

05_distributed.ipynb

The scheduler performance example in notebook 8 is showing different times than expected with the latest version of Dask. 
This cause the last 2 "questions to consider" to be confusing, since processes are faster than threads. I'm not sure why?
> ### Some Questions to Consider:
> - How much faster was using threads over a single thread? Why does this differ from the optimal speedup?
> - Why is the multiprocessing scheduler so much slower here?
```
import dask.dataframe as dd
import os
df = dd.read_csv(os.path.join('data', 'nycflights', '*.csv'),
parse_dates={'Date': [0, 1, 2]},
dtype={'TailNum': object,
'CRSElapsedTime': float,
'Cancelled': bool})
largest_delay = df[~df.Cancelled].DepDelay.max()
largest_delay
```
```
import time
for sch in ['threading', 'processes', 'sync']:
t0 = …
```

Update scheduler demo to illustrate performance differences

---

01_dask.delayed.ipynb

This PR updates a comment in the delayed notebook to indicate that `dask.delayed` uses the multi-threading scheduler by default (xref https://github.com/dask/dask/blob/7d09b9e505a2686d425b5fa240526583a250e62a/dask/delayed.py#L492)

Delayed uses multi-threaded scheduler by default

---

README.md

During the SciPy 2020 tutorial that is happening now, some users got confused about the
setup instructions and ended up following more than one of the options.
This commit clarifies that only one of those are necessary

Clarify that setup options are exclusive

---

03_array.ipynb
README.md

Fixes issue with running locally using the large weather dataset, process=False results in a multithreaded implementation according to the LocalCluster docs. This creates a lot of memory warning due to the overhead on the single process memory limit, whereas removing this results in a nice chew through the dataset with no warnings... 
Hope this suggestion helps! I suspect this would have solved a lot of chatter about speed/warnings in the live tutorial :-)

Fix Remove processes=False for Client

---

README.md

Further emphasizes that **only one** of the install paths should be chosen.

Changes to README: emphasize install

---

01x_lazy.ipynb

In part 3, delayed execution, the generator said 'yield y' when it should have said 'yield res'.

01x_lazy: typo in delayed execution

---

.dask/config.yaml

This is helpful for binder, where the default localhost link doesn't work.
(File copied from github.com/dask/dask-examples.)
Test: https://mybinder.org/v2/gh/willirath/dask-tutorial/patch-1?urlpath=lab

Configure dashboard to display proxied link

---

Dockerfile

The Dockerfile was creating an environment dask-tutorial but then launching jupyter using the default one.
This causes two issues:
1.  
2. Since the notebooks were not using the correct kernel, all packages used were not available and in particular graphviz was not available as pointed out in this [issue](https://github.com/dask/dask-tutorial/issues/139).
I fix that in this PR. It is not as straightforward as running `conda init` and the `conda activate environment` as the former requires to launch a new shell which is not possible. 
The solution is to shell into the correct environment and then run the postBuild script. Furthermore, the notebooks are configured to use the environment python3. This can be solved simply by pointing python3 to dask-tutorial as I have done.
In addition I …

Docker bug fix

---

.github/workflows/ci-build.yaml

setup-miniconda v2 fixes some deprecations in GitHub Actions. The project has also been moved to conda-incubator.

Bump GHA setup-miniconda version

---

01_dask.delayed.ipynb
01x_lazy.ipynb
02_bag.ipynb
03_array.ipynb
04_dataframe.ipynb
05_distributed.ipynb
06_distributed_advanced.ipynb

This PR contains typo fixes and minor editorial changes for the first few tutorials.

Typo fixes and minor editorial changes

---

binder/environment.yml

Let's temporarily pin JupyterLab to <3.0 until the extensions used here have been updated to be 3.0-compatible. As @ian-r-rose pointed out in https://github.com/dask/dask-tutorial/issues/202#issuecomment-759796901, the `jupyter_bokeh` extension hasn't been updated yet but progress is being tracked at https://github.com/bokeh/bokeh/issues/10569
Closes https://github.com/dask/dask-tutorial/issues/202

Pin jupyterlab<3

---

00_overview.ipynb
README.md

I gave a tutorial today and noticed that the overview notebook directs people to the old, unused gitter chat. That link should be replaced with one to the new Dask discourse forum, which is more active: https://dask.discourse.group/
Closes https://github.com/dask/dask-tutorial/issues/221
Related:
- https://github.com/dask/dask/pull/8332
- https://github.com/dask/community/issues/194

Direct questions/discussion to Dask discourse group

---

Dockerfile

When running from Dockerfile (option 2c in the README), the Docker image build process installs Jupyter Lab, but the running container uses a regular Jupyter notebook unless the user specifically navigates to `localhost:8888/lab`.  The Jupyter notebook environment ignores `source_hidden` metadata so all the answers are visible, taking all the fun out of the exercises.
This PR modifies the Dockerfile to run Jupyter Lab instead.  As a result, the startup link redirects to `localhost:8888/lab`, where hidden cells are hidden correctly by default.

Use Jupyter Lab when running from Dockerfile

---

03_array.ipynb

The sample code in the exercise [in the docs](https://tutorial.dask.org/03_array.html#Exercise:-Meteorological-data) contains an 'error' when rendered on the website. The problem entry is this:
> # complete the following:
> fig = plt.figure(figsize=(16, 8))
> plt.imshow(..., cmap='RdBu_r')
As I understand, this is meant to be there as a fill-in exercise to be completed during tutorial, but to avoid the error in the rendered version, perhaps it can placed in a markdown block... (there might be a better way to deal with this, e.g. marking some cells to be ignored during execution, but since it's just one cell here, maybe that would be excessive)

Avoid render error due to incomplete code

---

.github/workflows/ci-build.yaml
conf.py

On Monday, June 6th, dask.org will go live with a new design (see https://github.com/dask/community/issues/220). This PR is in preparation for the theme update for `dask-sphinx-theme` and can be merged in *after* https://github.com/dask/dask-sphinx-theme/pull/67 on Monday.
cc @jacobtomlinson @jsignell

Update docs theme for rebranding

---

README.md
binder/environment.yml

I know I had said that maybe we didn't need to specify numpy and pandas, but then it occurred to me that this env is meant to last for years, so it is probably a good idea to try to future-proof it a bit using pins. 
I also removed a bunch of packages that we no longer depend on and made the `conda install...` in the readme match the env.

Synchronize readme and env spec and put pins in env to mildly future-proof

---

README.md

I think SciPy 2022 was the last time this was presented, but happy to be corrected.

Update video to point to SciPy 2022

---

binder/environment.yml

Looks like 3.11 isn't supported yet
Rolling back to 3.10

Revert environment back to Python 3.10

---

README.md

For the ESIP tutorial we added some timings to help set audience expectations. Now that we've done it we can remove those again.

Revert ESIP timings
